#!/bin/bash 

# Generate cv pdf
make english 2>&1 > /dev/null
make spanish 2>&1 > /dev/null

# Generate cv png
# pdftoppm cv.pdf cv -png -singlefile

# Generate HTML
pandoc -s .githooks/cv-html.tex -o cv.html --title="" --metadata pagetitle="cv"

# Update README.md with the name of the current branch
#BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
#echo "![](https://github.com/ntallar/cv/blob/${BRANCH_NAME}/cv.png)" > README.md
rm README.md
echo "<h1>My CV</h1>" > README.md
tail -n +15 cv.html >> README.md

# Add changes to the current commit
git add README.md cv-en.pdf cv-sp.pdf
